//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademikBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notlar
    {
        public int OgrenciID { get; set; }
        public int DersID { get; set; }
        public Nullable<int> Sinav1 { get; set; }
        public Nullable<int> Sinav2 { get; set; }
        public Nullable<int> Sinav3 { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Tbl_Ogrenciler Tbl_Ogrenciler { get; set; }
        public virtual Tbl_Dersler Tbl_Dersler { get; set; }
    }
}
