//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademikBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesajlar
    {
        public int MesajID { get; set; }
        public Nullable<int> Gonderen { get; set; }
        public Nullable<int> Alıcı { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Tbl_Ogrenciler Tbl_Ogrenciler { get; set; }
        public virtual Tbl_Ogrenciler Tbl_Ogrenciler1 { get; set; }
    }
}
