//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademikBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Duyurular
    {
        public int DuyuruID { get; set; }
        public string DuyuruBaslik { get; set; }
        public string DuyuruIcerik { get; set; }
        public Nullable<int> DuyuruGönderen { get; set; }
        public Nullable<System.DateTime> DuyuruTarih { get; set; }
    
        public virtual Tbl_Ogretmenler Tbl_Ogretmenler { get; set; }
    }
}
