//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademikBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ogretmenler()
        {
            this.Tbl_Duyurular = new HashSet<Tbl_Duyurular>();
        }
    
        public int OgrtID { get; set; }
        public string OgrtAd { get; set; }
        public string OgrtSoyad { get; set; }
        public string OgrtFotograf { get; set; }
        public Nullable<int> OgrtSifre { get; set; }
        public string OgrtUniversite { get; set; }
        public string OgrtUnvan { get; set; }
        public string OgrtMail { get; set; }
        public Nullable<int> OgrtTelefon { get; set; }
        public Nullable<int> OgrtBrans { get; set; }
    
        public virtual Tbl_Dersler Tbl_Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Duyurular> Tbl_Duyurular { get; set; }
    }
}
