//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademikBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ogrenciler()
        {
            this.Tbl_Mesajlar = new HashSet<Tbl_Mesajlar>();
            this.Tbl_Mesajlar1 = new HashSet<Tbl_Mesajlar>();
            this.Tbl_Notlar = new HashSet<Tbl_Notlar>();
        }
    
        public int Ogr_ID { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrFotograf { get; set; }
        public string OgrTelefon { get; set; }
        public string OgrMail { get; set; }
        public string OgrSifre { get; set; }
        public string OgrUniAdi { get; set; }
        public string OgrFakulteAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Mesajlar> Tbl_Mesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Mesajlar> Tbl_Mesajlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notlar> Tbl_Notlar { get; set; }
    }
}
